#!/usr/bin/env bash

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ];then
    exec gosu $WWWUSER "$@"
else
    /usr/bin/supervisord
fi


composer install
./vendor/bin/sail up
docker exec -it gilson_test_app sh -c 'php artisan migrate'
docker exec -it gilson_test_app sh -c 'php artisan queue:work --queue=high,default'